CREATE TABLE type (
	id SERIAL PRIMARY KEY,
	name VARCHAR(20) NOT NULL
);

CREATE TABLE product (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL UNIQUE,
	type_id INTEGER REFERENCES type (id),
	expired_date TIMESTAMP, 
	price DOUBLE PRECISION,
	num INTEGER NOT NULL
);